---
version: '3'
services:
  freqtrade_ichiV1:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: freqtrade_ichiV1
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade_ichiV1.log
      --db-url sqlite:////freqtrade/user_data/dbs/freqtrade_ichiV1.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy ichiV1
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"
      - "./user_data:/user_data"
volumes:
  grafana-storage: