{
 "title": "Freqtrade",
 "description": "Freqtrade information from postgres database",
 "tags": [
  "freqtrade",
  "application"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster name",
    "query": {
     "query": "label_values(freqtrade_build_info, cluster)"
    }
   },
   {
    "name": "strategy",
    "label": "Strategy name",
    "query": {
     "query": "label_values(freqtrade_build_info{cluster=~\"$cluster\"}, strategy)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Strategy performance / Profit",
   "type": "timeseries",
   "description": "This will show profit as percent thought history.\n(fthelper: v4.4.4)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(cluster, strategy) (freqtrade_perf_realized_pct)",
     "legendFormat": "Realized - {{ cluster }} - {{ strategy }}"
    }
   ]
  },
  {
   "title": "Strategy performance / Success rate",
   "type": "timeseries",
   "description": "This will show percentage of winning compare to total trades\n(fthelper: v3.x.x)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(cluster, strategy) (freqtrade_trade_winning / freqtrade_trade_close)",
     "legendFormat": "Success rate - {{ cluster }} - {{ strategy }}"
    }
   ]
  },
  {
   "title": "Summary - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Balance",
     "type": "timeseries",
     "description": "Balance we has in exchange. Difference is first - last value in graph. Range is Max Drawdown",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg by(cluster, strategy, stake) (freqtrade_crypto_balance{cluster=\"$cluster\", strategy=~\"$strategy\"})",
       "legendFormat": "{{ stake }}"
      },
      {
       "expr": "avg by(cluster, strategy, stake) (freqtrade_fiat_balance{cluster=\"$cluster\", strategy=~\"$strategy\"})",
       "legendFormat": "{{ stake }}"
      }
     ]
    },
    {
     "title": "Profit",
     "type": "gauge",
     "description": "This will calculate base on dashboard time range.",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "diffperc" ] } },
     "targets": [
      {
       "expr": "avg by(cluster, strategy) (freqtrade_crypto_balance{cluster=\"$cluster\", strategy=~\"$strategy\"})",
       "legendFormat": "{{ version }} - {{ stake }}"
      }
     ]
    },
    {
     "title": "Latest trade",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "dtdurations" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freqtrade_trade_latest_seconds{cluster=\"$cluster\", strategy=~\"$strategy\"} - time()"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freqtrade_build_info{cluster=\"$cluster\"}",
       "legendFormat": "{{ strategy }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freqtrade_state{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Win trade",
     "type": "stat",
     "description": "This will show win trade with specify time window",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "expr": "avg by(cluster, strategy) (freqtrade_trade_winning{cluster=\"$cluster\", strategy=~\"$strategy\"})"
      }
     ]
    },
    {
     "title": "Loss trade",
     "type": "stat",
     "description": "This will show losing trade within specify time window",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "range" ] } },
     "targets": [
      {
       "expr": "avg by(cluster, strategy) (freqtrade_trade_losing{cluster=\"$cluster\", strategy=~\"$strategy\"})"
      }
     ]
    },
    {
     "title": "Current open trade",
     "type": "stat",
     "description": "Number is current open trades",
     "gridPos": { "h": 4, "w": 3, "x": 14, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "avg by(cluster, strategy) (freqtrade_trade_open_current{cluster=\"$cluster\", strategy=~\"$strategy\"})"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 17, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freqtrade_build_info{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "freqtrade_mode{cluster=\"$cluster\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Detailed - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "cluster",
   "collapsed": true,
   "panels": [
    {
     "title": "Current holding cryptocurrency",
     "type": "table",
     "gridPos": { "h": 9, "w": 14, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "freqtrade_crypto_balances{cluster=~\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Locked pairs",
     "type": "timeseries",
     "description": "This will show historical of locking pairs.\n(fthelper: v3.x.x)\n",
     "gridPos": { "h": 9, "w": 10, "x": 14, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "freqtrade_lock_count{cluster=~\"$cluster\", strategy=~\"$strategy\"}",
       "legendFormat": "Current locks"
      }
     ]
    },
    {
     "title": "Profit / Pair",
     "type": "table",
     "description": "This comparing profit of each pair as percent gain.\n(fthelper: v4.0.0)",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "freqtrade_pair_profit_pct{cluster=~\"$cluster\", strategy=~\"$strategy\"}",
       "legendFormat": "{{ pair }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Internal",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 },
   "collapsed": true,
   "panels": [
    {
     "title": "Freqtrade success rate",
     "type": "timeseries",
     "description": "Success rate when ftmetric call to freqtrade server",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max without(type) (fthelper_internal_ft_call{cluster=~\"$cluster\", type=\"success\"}) / max without(type) (fthelper_internal_ft_call{cluster=~\"$cluster\", type=\"total\"})",
       "legendFormat": "success - {{ cluster }}"
      }
     ]
    },
    {
     "title": "Freqtrade cache rate",
     "type": "timeseries",
     "description": "How many percent of total request that we cached",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(freqtrade_internal_cache_total{cluster=~\"$cluster\"} - freqtrade_internal_cache_miss{cluster=~\"$cluster\"}) / freqtrade_internal_cache_total{cluster=~\"$cluster\"}",
       "legendFormat": "cache rate - {{ cluster }}"
      }
     ]
    },
    {
     "title": "Freqtrade total call",
     "type": "timeseries",
     "description": "How many we call to freqtrade",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(fthelper_internal_ft_call{cluster=~\"$cluster\", type=\"total\"}[5m])",
       "legendFormat": "{{ cluster }}"
      }
     ]
    },
    {
     "title": "Freqtrade log level",
     "type": "timeseries",
     "description": "How many log level are logged in freqtrade server. You can enabled warning level in disabled query.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "targets": [
      {
       "expr": "sum by(cluster) (freqtrade_log_level{cluster=~\"$cluster\", level=\"ERROR\"})",
       "legendFormat": "Error - {{ cluster }}"
      }
     ]
    },
    {
     "title": "Warmup duration",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(fthelper_internal_warmup_duration_bucket[5m])) by (le))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(fthelper_internal_warmup_duration_bucket[5m])) by (le))",
       "legendFormat": "P50"
      }
     ]
    },
    {
     "title": "Warmup success rate",
     "type": "timeseries",
     "description": "Every time warmup trigger, It perform several process. This graph will breakdown each process and calculate success rate of overall",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "fthelper_internal_warmup", "legendFormat": "{{ job }}" }
     ]
    }
   ]
  }
 ]
}