---
version: '3'
services:
  hippo_SMAOffset:
    # image: freqtrade_custom
    image: freqtradeorg/freqtrade:stable
    # image: freqtradeorg/freqtrade:develop
    # Use plotting image
    # image: freqtradeorg/freqtrade:develop_plot
    # # Enable GPU Image and GPU Resources (only relevant for freqAI)
    # # Make sure to uncomment the whole deploy section
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    # Build step - only needed when additional dependencies are needed
    # build:
    #   context: .
    #   dockerfile: "./docker/Dockerfile.custom"
    restart: unless-stopped
    container_name: hippo_SMAOffset
    volumes:
      - "../user_data:/freqtrade/user_data:rw"
    ports:
      - "8080:8080"
    # Default command used when running `docker compose up`
    command: >
      trade
      --logfile /freqtrade/user_data/logs/SMAOffset_Hippocritical_dca.log
      --db-url sqlite:////freqtrade/user_data/dbs/SMAOffset_Hippocritical_dca.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy SMAOffset_Hippocritical_dca

  NostalgiaForInfinityV7:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: NostalgiaForInfinityV7
    volumes:
      - "../user_data:/freqtrade/user_data:rw"
    ports:
      - "8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/NostalgiaForInfinityV7.log
      --db-url sqlite:////freqtrade/user_data/dbs/NostalgiaForInfinityV7.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy NostalgiaForInfinityV7

  HPStrategy:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: HPStrategy
    volumes:
      - "../user_data:/freqtrade/user_data:rw"
    ports:
      - "8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/HPStrategy.log
      --db-url sqlite:////freqtrade/user_data/dbs/HPStrategy.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy HPStrategy
