---
version: '3'
services:

  NostalgiaForInfinityX4_01_28:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: NostalgiaForInfinityX4_01_28
    volumes:
      - "../user_data:/freqtrade/user_data"
    ports:
      - "8082:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/NostalgiaForInfinityX4_01_28.log
      --db-url sqlite:////freqtrade/user_data/dbs/NostalgiaForInfinityX4_01_28.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy NostalgiaForInfinityX4_01_28

  NotAnotherSMAOffsetStrategy:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: NotAnotherSMAOffsetStrategy
    volumes:
      - "../user_data:/freqtrade/user_data"
    ports:
      - "8083:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/NotAnotherSMAOffsetStrategy.log
      --db-url sqlite:////freqtrade/user_data/dbs/NotAnotherSMAOffsetStrategy.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy NotAnotherSMAOffsetStrategy

  HPStrategy_12_27:
    image: freqtradeorg/freqtrade:stable
    restart: unless-stopped
    container_name: HPStrategy_12_27
    volumes:
      - "../user_data:/freqtrade/user_data"
    ports:
      - "8084:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/HPStrategy_12_27.log
      --db-url sqlite:////freqtrade/user_data/dbs/HPStrategy_12_27.sqlite
      --config /freqtrade/user_data/configs/config.json
      --strategy HPStrategy_12_27