{
 "title": "Freqtrade-dryruns_v2",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "dryrun_databases",
    "query": "select distinct identifier from trades"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<center>\n    <img src=\"https://i.ibb.co/dQStsLY/Frequenthippo-white.png\" alt=\"FHBT\" style=\"border: 0;\">\n</center>\n"
   }
  },
  {
   "title": "overall dryrun count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 0 },
   "targets": [
    {
     "rawSql": "select drylive_runs_count from precalc_drylive_and_backtest_stats "
    }
   ]
  },
  {
   "title": "readme",
   "type": "text",
   "gridPos": { "h": 11, "w": 16, "x": 8, "y": 0 },
   "options": {
    "content": "This Grafana server is a data output of all dry runs (and some live).<br>\n\n<p style=\"color:red;\"><b>Links to related dashboards are in the top right</b></p>\n\nIn the top, you see some general properties of the data and currently the list of checked strategies for look ahead bias.<br>\n\nBelow that, you see a general chart of a 90d default period (which can be expanded, in time range as you like; look at the last year's data, for example).<br>\n\nAgain below that is a list of strategies with more details.<br>\n\n<h3>If you want to join our Discord of crypto trading enthusiasts, you are most welcome. <a style=\"color:teal; text-decoration:underline;\" href=\"https://discord.gg/yzU6SQpDxN\">https://discord.gg/yzU6SQpDxN</a></h3>\n\n<h3>Referral links</h3>\n\nAll live runs are currently run on Vultr in Tokyo (Binance.com and Kucoin.com). <a style=\"color:teal; text-decoration:underline;\" href=\"https://www.vultr.com/?ref=8902029\">https://www.vultr.com/?ref=8902029</a><br>\n\nBinance, 10% fees deduction for you: <a style=\"color:teal; text-decoration:underline;\" href=\"https://accounts.binance.com/en/register?ref=M2Q6Q8YI\">https://accounts.binance.com/en/register?ref=M2Q6Q8YI</a><br>\n\nKucoin, 20% lifetime fees deduction: <a style=\"color:teal; text-decoration:underline;\" href=\"https://www.kucoin.com/r/af/QBSSS165\">https://www.kucoin.com/r/af/QBSSS165</a><br>\n\nGateio, 20% fees deduction: <a style=\"color:teal; text-decoration:underline;\" href=\"https://www.gate.io/signup/10902928\">https://www.gate.io/signup/10902928</a><br>\n\n"
   }
  },
  {
   "title": "overall days of data",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 3 },
   "targets": [
    {
     "rawSql": "select drylive_days_of_data from precalc_drylive_and_backtest_stats"
    }
   ]
  },
  {
   "title": "most recent trade happened at",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select drylive_latest_closed_trade from precalc_drylive_and_backtest_stats"
    }
   ]
  },
  {
   "title": "overall trade count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select drylive_trade_count from precalc_drylive_and_backtest_stats"
    }
   ]
  },
  {
   "title": "Profit on a base of 500$ static stakes (for dry runs)",
   "type": "timeseries",
   "description": "this only contains data of CLOSED trades.\n\nFor open trades see the rows below!",
   "gridPos": { "h": 37, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT \n    metric, \n    time, \n    value \nFROM \n    profit_trades_selected(\n        TO_TIMESTAMP(${__from} / 1000)::date::timestamp, \n        TO_TIMESTAMP(${__to} / 1000)::date::timestamp, \n        regexp_split_to_array('${dryrun_databases:csv}', ',')\n    );\n"
    }
   ]
  },
  { "title": "${dryrun_databases}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 }, "repeat": "dryrun_databases" },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM open_trades(${dryrun_databases}) As \"Open Trades\";"
    },
    {
     "rawSql": "select drylive_closed_trades\nfrom precalc_drylive_identifier_stats\nwhere identifier = $dryrun_databases"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 3, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select drylive_avg_profit\nfrom precalc_drylive_identifier_stats\nwhere identifier = $dryrun_databases"
    },
    {
     "rawSql": "select drylive_abs_profit\nfrom precalc_drylive_identifier_stats\nwhere identifier = $dryrun_databases"
    }
   ]
  },
  {
   "title": "Profit",
   "type": "timeseries",
   "description": "This chart always starts at 0 for the given timerange,.\nFor a full view please use a larger timerange if you don't see profit and the end of this chart line up.",
   "gridPos": { "h": 7, "w": 6, "x": 5, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawSql": "SELECT * FROM profit(${dryrun_databases}, TO_TIMESTAMP(${__from} / 1000)::date::timestamp, TO_TIMESTAMP(${__to} / 1000)::date::timestamp)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Currently open trades",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawSql": "SELECT * FROM open_trades_MinMaxState(${dryrun_databases})",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Avg trade duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawSql": "select drylive_avg_trade_duration\nfrom precalc_drylive_identifier_stats\nwhere identifier = $dryrun_databases",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Profit distribution",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawSql": "SELECT * FROM profit_distribution(${dryrun_databases});",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "$ of simultaneously opened stakes (calculated by trade max_stake_amount, not orders! this is a worst case!)",
   "type": "timeseries",
   "description": "This chart sums up how much $ a trade uses.\nIt will only look at the overall $ a trade uses, not take the orders into its' context. This chart thereby is a worst-case.\nReal results might have varied in some cases.",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawSql": "SELECT * FROM performance_by_dollar_invested(${dryrun_databases}, TO_TIMESTAMP(${__from} / 1000)::date::timestamp, TO_TIMESTAMP(${__to} / 1000)::date::timestamp)",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "trade sizes",
   "type": "table",
   "description": "This chart shows you how deep (if it is a DCA strategy that is rebuying in) \nsee freqtrade.io => adjust_trade_position for more info\nFor all non-dca-strategies this chart is not of any value.",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "\n    SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value\n    WHERE time >= 1234 and time < 134567\n  ",
     "rawQueryText": "SELECT CAST(strftime('%s', 'now', '-1 minute') as INTEGER) as time, 4 as value \nWHERE time >= $__from / 1000 and time < $__to / 1000",
     "rawSql": "with list1 as (SELECT ROUND(stake_amount::numeric,0) as stake_amount FROM trades WHERE identifier IN (${dryrun_databases}))\nselect count(stake_amount) as occurency, stake_amount from list1 \ngroup by stake_amount",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}